# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-11 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20200303_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='hash_url',
            field=models.CharField(max_length=32, null=True, verbose_name='URL'),
        ),
    ]
